name: Node CI

on:
  - push

jobs:
  linting: 

    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          make install
      - name: Run linter
        run: |
          make lint